### PR TITLE
Handle stdout and stderr as {ok, _} and {error, _}

### PR DESCRIPTION
**Pull request by hrobeers**
Fixes issue #10 
Pipes will now exit on error instead of piping the error output to the next process in the pipe.

Also improved readability of unit tests.
Check the unit tests to see the implications of these changes.

I hope you like these changes.

### CODE REVIEW

**Comment by hrobeers** [comment]
While integrating this lib in my project, I found out that erlang ports sometimes return the stdout stream as a list of multiple binaries. I'm not sure why, but it made the check_err function fail.

Therefore I added another commit that makes sure that a binary is returned instead of an iolist.

**Comment by mattsta** [comment]
> sometimes return the stdout stream as a list of multiple binaries.

Good point.  The original purpose of returning iolists (just what the port returned from itself) was to be more efficient if we're just forwarding to a file writer or network socket.  For small values, the extra conversion doesn't matter and the speed difference won't be noticeable, but for high throughput or larger values (multi-hundred-MB or GB-sized values), an unnecessary iolist_to_binary can be noticeable.

(As for the tests cases failing, you [removed my `iolist_to_binary` conversion](https://github.com/hrobeers/erlang-stdinout-pool/commit/ccf23364d114168c4d7ec38b0a0ac3da97bbc552#diff-112a1af01d7c81e227cdeaa690f416aeL6) in the test cases, so they started failing!  But, you went back and fixed it! (by binary-izing everything in the API itself.)  :-D)

> I'm not sure why, but it made the check_err function fail.

Oh, that's simple.  Your guards were `check_err([<<145, Tail/binary>>])` but an iolist would sometimes be something like `[<<145, A, B>>, [C, D, E], ...]`.  It could be handled (untested/unchecked) with: `check_err([<<145, Tail/binary>> | Rest]) -> {ok, [<<Tail/binary>> | Rest]};` and still be a proper iolist.

Thanks for fixing all of this.  Hopefully I'll get around to double checking everything and get it officially added soon.  I may change some tiny things (like renaming `ok`/`error` tuples to `{stdout, X}` and `{stderr, X}`), but overall it looks really great. :shipit:

**Comment by hrobeers** [comment]
Thanks for accepting these changes.

I'm actually just learning Erlang. As I want to use it in my project to expose c++ applications as a webservice. I'm now trying out leptus (https://github.com/s1n4/leptus).

This was a great learning experience! So I'll keep watching this to see you improve this code.

**Comment by mattsta** [comment]
Cleaned this up a bit at https://github.com/mattsta/erlang-stdinout-pool/commits/improve/api/retrieve/stdout-vs-stderr

The only major changes are renaming ok->stdout and error->stderr (we were already using `error` to signal actual error conditions elsewhere, so it's cleaner to break out specific meanings) and allowing `check_err/1` to accept an iolist instead of needing to flatten all binaries first.

Give the new branch a review and if it all still looks good to you, I'll promote your changes to master and bump the version to 2.0.

Thanks for all the improvements!

**Comment by hrobeers** [comment]
It works perfect for me.
Thanks for taking the time to clean it up.
It was a great learning experience.

**Pull request closed without merging**
